name: oauth_forked
version: 0.4.0
authors:
  - Tobe O (maintainer) <thosakwe@gmail.com>
  - Owen Shepherd <*@owenshepherd.net>
description: An implementation of OAuth 1.0a per RFC 5849
homepage: https://github.com/thosakwe/oauth.dart
environment:
    sdk: ">=2.0.0 <3.0.0"
dependencies:
  # cipher: '>=0.7.0 <0.8.0'
  crypto: '^2.0.1'
  http: ^0.12.0
  pointycastle: ^1.0.0
dev_dependencies:
  shelf: '>=0.6.7+2'
  test: ^1.0.0
